# Generated by Django 5.1.7 on 2025-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/clientes/'),
        ),
        migrations.AddField(
            model_name='perfilfuncionario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/funcionarios/'),
        ),
    ]
