# Generated by Django 5.1.7 on 2025-06-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_perfilcliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcliente',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='perfilfuncionario',
            name='foto_perfil',
        ),
    ]
